import Header from '@/components/Header'
import './globals.css'
import '@/styles/github-dark.css'
import { Inter } from 'next/font/google'
import Providers from '@/components/Providers'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-stone-50 dark:bg-stone-950`}>
        <Providers>
          <Header />
          <main className="mx-auto mt-40 min-h-screen max-w-3xl">
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
